foreground              #FFFFFF
background              #070009
selection_foreground    #070009
selection_background    #FFFFFF
cursor                  #7F2277 
cursor_text_color       #FFFFFF

active_tab_foreground     #070009
active_tab_background     #1F0672
inactive_tab_foreground   #1F0672
inactive_tab_background   #070009

# black
color0      #492952
color8      #82578F

# red
color1      #FFCCFB
color9      #F0AAEA

# green
color2      #EECCFF
color10     #D8AAF0

# yellow
color3      #D8CCFF
color11     #BAAAF0

# blue
color4      #D59AE6
color12     #D59AE6

# magenta
color5      #CC9AE6
color13     #CC9AE6

# cyan
color6      #AB9AE6
color14     #AB9AE6

# white
color7      #FFCCFB
color15     #F0AAEA
