general {
    col.active_border = rgba(EFE5F6ff) rgba(1A1A1Aff) 45deg
    col.inactive_border = rgba(101010ff) rgba(272727ff) 45deg
}

group {
    col.border_active = rgba(EFE5F6ff) rgba(1A1A1Aff) 45deg
    col.border_inactive = rgba(101010cc) rgba(272727cc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(030303ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
