general {
    col.active_border = rgba(EECBB6ff) rgba(1A1A1Aff) 45deg
    col.inactive_border = rgba(020202ff) rgba(4B3736ff) 45deg
}

group {
    col.border_active = rgba(EECBB6ff) rgba(1A1A1Aff) 45deg
    col.border_inactive = rgba(020202cc) rgba(4B3736cc) 45deg
    col.border_locked_active = rgba(DDDEDFff) rgba(070708ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
