general {
    col.active_border = rgba(FAEFC6ff) rgba(524929ff) 45deg
    col.inactive_border = rgba(333130ff) rgba(534C47ff) 45deg
}

group {
    col.border_active = rgba(FAEFC6ff) rgba(524929ff) 45deg
    col.border_inactive = rgba(333130cc) rgba(534C47cc) 45deg
    col.border_locked_active = rgba(121213ff) rgba(050505ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
